<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-07T21:19:41 ART" name="Default suite" finished-at="2022-02-07T21:20:00 ART" duration-ms="19392">
    <groups>
    </groups>
    <test started-at="2022-02-07T21:19:41 ART" name="Default test" finished-at="2022-02-07T21:20:00 ART" duration-ms="19392">
      <class name="pruebas.CreateOrder_DataProviderTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:pruebas.CreateOrder_DataProviderTest@36bc55de]" started-at="2022-02-07T21:19:29 ART" name="setUp" finished-at="2022-02-07T21:19:41 ART" duration-ms="11969" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="createOrder(java.lang.String,java.lang.String)[pri:0, instance:pruebas.CreateOrder_DataProviderTest@36bc55de]" started-at="2022-02-07T21:19:41 ART" name="createOrder" data-provider="Datos Login" finished-at="2022-02-07T21:19:45 ART" duration-ms="4073" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrder -->
        <test-method signature="createOrder(java.lang.String,java.lang.String)[pri:0, instance:pruebas.CreateOrder_DataProviderTest@36bc55de]" started-at="2022-02-07T21:19:45 ART" name="createOrder" data-provider="Datos Login" finished-at="2022-02-07T21:19:54 ART" duration-ms="8377" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[performance_glitch_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrder -->
        <test-method signature="createOrder(java.lang.String,java.lang.String)[pri:0, instance:pruebas.CreateOrder_DataProviderTest@36bc55de]" started-at="2022-02-07T21:19:54 ART" name="createOrder" data-provider="Datos Login" finished-at="2022-02-07T21:19:57 ART" duration-ms="3374" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[problem_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrder -->
        <test-method signature="createOrder(java.lang.String,java.lang.String)[pri:0, instance:pruebas.CreateOrder_DataProviderTest@36bc55de]" started-at="2022-02-07T21:19:57 ART" name="createOrder" data-provider="Datos Login" finished-at="2022-02-07T21:20:00 ART" duration-ms="3053" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at pruebas.CreateOrder_DataProviderTest.createOrder(CreateOrder_DataProviderTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:pruebas.CreateOrder_DataProviderTest@36bc55de]" started-at="2022-02-07T21:20:00 ART" name="tearDown" finished-at="2022-02-07T21:20:00 ART" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- pruebas.CreateOrder_DataProviderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
